### ISSUE TITLE
Branches clean up

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Toplo#132]
@plantec @labordep 
do you agree to delete all the branches in the capture EXCEPT: 
- **dev**
- **master**
- **ToSelectionModelSelecter** (it has 2 weeks without changes but it doesn't look merged)
- **Pharo12** (I've created it today, this will be a stable branch similar to master, but even more stable, that we ensure newcomers that are in Pharo12 click on a World Menu entry to load it)

<img width="958" alt="Screenshot 2024-04-09 at 17 16 30" src="https://github.com/pharo-graphics/Toplo/assets/3044265/53ec305e-cbc2-4c54-a4eb-979909a05b29">

**Comment by plantec** [comment]
ok for me.
ToSelectionModelSelecter can be removed too
thanks

**Comment by tinchodias** [comment]
done!
