### ISSUE TITLE
[ToLabel] Define Font Name on ToTheme

### ISSUE THREAD

**Issue by LANDAISB** [pharo-graphics/Toplo#134]
I failed to set a Font with a custom ToTheme.
I try this:
 
```
	self select: ToLabel asTypeSelector style: [
		self when: ToInstallLookEvent write: (self property: #'text-attributes-with-builder') with: [:e |
                        e textAttributesBuilder defaultFontName: 'Univia Pro'.
			e textAttributesBuilder fontName: 'Univia Pro'.
                        e textAttributesBuilder fontSize: 32.
                        e textAttributesBuilder foreground: (Color red).
		].
        ]
```
=> Only fontSize and color are modified, the font is not changed.

With Bloc I use this:
`BlTextElement new text: ('lmonijqgys 8' asRopedText foreground: Color red; fontSize: 32;fontName: 'Univia Pro').`
=> This works

This font Univia is loaded from local directory "<MyImageDirectory>/assets/fonts/Univia" :
`AeFontManager globalInstance scanDirectory: 'assets/fonts/Univia/' asFileReference.`

**Comment by plantec** [comment]
can you upload the full theme definition please ?
use a file-out  from the browser, context menu on the class, 'Extra/File Out'

**Comment by LANDAISB** [comment]
[TestTheme.txt](https://github.com/pharo-graphics/Toplo/files/14933254/TestTheme.txt)

I attach the .st file (but I rename it on .txt)

**Comment by plantec** [comment]
it should work now after my last commit (in Toplo:dev)
The theme API has changed.
Now we have :
- for the default theme (installed in the space) BlSpace>>toTheme/toTheme: 
- for a BlElement>>localTheme/localTheme:  for getting changing a particular element theme
- for getting the space theme from an element: lookupTheme
BlElement>>localStyleSheetTheme: has been removed

**Comment by LANDAISB** [comment]
It works well now, thanks a lot.
