### ISSUE TITLE
Bug: ToTextField

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Toplo#145]
Hello,

I found a bug on the ToTextField.
The text is displayed in front of the blue shape but it should be displayed behind it.

```st
background := BlElement new background: Color red; yourself.
helloWorld := ToTextField new text: 'Hello world'.
foreground := BlElement new background: Color blue; position: 10 @ 0; yourself.

space := BlSpace new.
space root addChild: background.
space root addChild: helloWorld.
space root addChild: foreground.

space show
```
![image](https://github.com/pharo-graphics/Toplo/assets/34318678/a084a8ec-98b7-4deb-a57b-4a00c36690bf)

**Comment by tinchodias** [comment]
Sorry for answering so late. In this case, I think the idea is avoiding re-rendering the text if it didn't change. Else, each cursor blink produces rendering each word again.

My space new looks like this:

<img width="109" alt="Screenshot 2024-09-24 at 17 58 29" src="https://github.com/user-attachments/assets/ba70ef6c-57bb-491c-9e9b-0f6960db1d97">

Do we close the issue?

**Comment by Nyan11** [comment]
Yes, the bug is no more present on my side.
