### ISSUE TITLE
Creating a ToButton with a background doesn't apply the background

### ISSUE THREAD

**Issue by Eliott-Guevel** [pharo-graphics/Toplo#157]
Applying a background to a `ToButton` then adding it to a `BlSpace` doesn't apply it.
It does apply it in the `BlSpace` preview though.

![buttonBackground](https://github.com/pharo-graphics/Toplo/assets/76944457/d30b08d5-31a6-419c-9dd6-d3ef94b8dab4)

To reproduce:
```smalltalk
aSpace := BlSpace new
    position: 50 asPoint;
    show; 
    yourself.

button := ToButton new 
    labelText: 'Button';
    size: 100 @ 100;
    background: Color red.

aSpace root addChild: button
```

Also does it in this order:
```smalltalk
    size: 100 @ 100.

aSpace root addChild: button.
button background: Color red.
```

Currently, the method must be executed after the window is shown.
Instead, it would be better if executing the displayed code changed its background.

**Comment by plantec** [comment]
Toplo widgets look are managed by a skin.
If you don't want to use the default skin then send #withNullSkin to the button.
But don't expect it to adapt itself when hovered, leaved, pressed, ...
other solutions are to define you own skin/theme or to not use Toplo button.

```
aSpace := BlSpace new
    position: 50 asPoint;
    show; 
    yourself.

button := ToButton new withNullSkin;
    labelText: 'Button';
    size: 100 @ 100;
    background: Color red.

aSpace root addChild: button```

**Comment by plantec** [comment]
can we close this issue ?
