### ISSUE TITLE
Changing the background of a ToButton doesn't work as expected

### ISSUE THREAD

**Issue by Eliott-Guevel** [pharo-graphics/Toplo#158]
Changing the background of a ToButton through `background: ` (after the window has been launched, see #157) make it revert back to white after hovering on the button. 
This is due to the fact that it uses the raw theme (`ToGeneralButtonSkin`).

Currently, a workaround takes the form of
```smalltalk
addTokenNamed: #'color-bg-container' withValue: Color color
```
which isn't really intuitive. 
Instead, it would be better to change the behavior of `background: ` so that it doesn't revert its color back to white after being hovered on.

**Comment by plantec** [comment]
you can send #withNullSkin to the button (related to issue #157)

**Comment by plantec** [comment]
can we close this issue ?
