### ISSUE TITLE
Error ToElementPropertyNotFound: double-click-delay

### ISSUE THREAD

**Issue by LouisePla** [pharo-graphics/Toplo#175]
I have a list displayed with a custom theme and when I double-click on an item in the list, I have a ToElementPropertyNotFound error: double-click-delay.

I have the impression that the handler is looking for the token called #'double-click-delay', which must be in the BeeTheme by default, but that I do not have in my theme. 

![image](https://github.com/pharo-graphics/Toplo/assets/123971303/3bf7fd0c-0e08-40de-bb66-0fcbd070b7fc)

**Comment by plantec** [comment]
just adding the missing token in your theme in not working ?

**Comment by LouisePla** [comment]
It works :) I forgot to close the ticket
