### ISSUE TITLE
554 tests are broken!

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Toplo#185]
We have 554 tests broken

- Can we have a real process?
- Did I integrate something wrong?
- There is one event that does exist anymore
- Can we learn from this?

```
eventsToHandle

	^ {
		  ToLayoutDirectionChangedEvent.
		  ToLayoutOrientationChangedEvent.
		  BlLayoutConstraintsChangedEvent }
```

**Comment by Ducasse** [comment]
I do not get it the GH action are green.

**Comment by Ducasse** [comment]
I could not find what removed BlLayoutConstraintsChangedEvent from Bloc. 
It is ok to remove it?

**Comment by Ducasse** [comment]
I was loading the master branch of Toplo no idea if this is good.

**Comment by Ducasse** [comment]
@tinchodias 
Hi martin why this issue is still open. 
I will fix it but I do not really get it. 
Having green tests is super important.

**Comment by Ducasse** [comment]
Broken tests were in master but they are green in dev. 
So after merging dev into master it will be ok

**Comment by tinchodias** [comment]
I missed the notification since last week. So I see you are doing a big pass, probably pair-programming with Alain, right?  I see #190

**Comment by Ducasse** [comment]
Yes. I want to have a green bar and also make sure that we have smoke tests for all the examples. 
Check what I did in Toplo-Examples.
