### ISSUE TITLE
Can we have a test that checks that the Toplo examples are working?

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Toplo#187]
Hi guys

8 or 10 months ago I asked if we can have single dummy test that execute all the Toplo example and report if they fail.
And they fail. 

When can we act a bit to avoid to damage our feeling that we go in the right direction?

**Comment by Ducasse** [comment]
I'm working on it.

**Comment by plantec** [comment]
the 3 mock tests are skipped because running them automatically breaks the checking done in GitHub.
I guess this is related to the the window closing that is not working well in all cases

**Comment by tinchodias** [comment]
@plantec I think you fixed this issue, no?
