### ISSUE TITLE
[Post-mortem] UndefinedObject(Object)>>doesNotUnderstand: #advance

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Toplo#208]
![image](https://github.com/user-attachments/assets/74c464de-a0fe-40e3-b410-7fb481b5ac1b)

Exception when click on a Toplo text editor.

Pharo 12 latest.

**Comment by labordep** [comment]
@LANDAISB do you have more informations?

**Comment by plantec** [comment]
yes :) difficult to investigate more without more precise description of the context

**Comment by labordep** [comment]
:(

**Comment by labordep** [comment]
@plantec before this exception, we have this one:
![toplo_LI](https://github.com/user-attachments/assets/8355b1c9-d950-41ad-a413-304d39f1353b)

**Comment by labordep** [comment]
This error was due to modification of model during the layout phase.
This is fixed by copying datas before using nodeBuilder:.
