### ISSUE TITLE
Replace BLRBTextStyler by Shout

### ISSUE THREAD

**Issue by jecisc** [pharo-graphics/Toplo#88]
It would be nice to use the text styler of Pharo instead of having one specific to Album to reduce duplication and the need to maintain two stylers. (Alain agreed)

**Comment by tinchodias** [comment]
Are you interested on this task @jecisc  ?

**Comment by jecisc** [comment]
I tried to do it already but examples using syntax highlight were broken so and I did not know Toplo enough to do the change "in the dark".

I'm interested to do it but I don't have the time right now and I'll have a few weeks of holidays soon

**Comment by tinchodias** [comment]
The deprecation message in the trait that `BlRBTextStyler` uses, suggests creating a subclass of `RBProgramNodeVisitor`. Is this the Shout solution?

**Comment by tinchodias** [comment]
Okay, I wrote too fast: immediately I've found `SHRBTextStyler`

**Comment by tinchodias** [comment]
The main particularity I detect when I read the code of `BlRBTextStyler` in reference to `SHRBTextStyler` is creating instances in the hierarchy of `BlTextLinkAttribute`. But, as you can see in the screen capture... this hierarchy is stub, it does nothing special; it ignores the names it receives:

<img width="650" alt="Screenshot 2024-07-04 at 12 48 33" src="https://github.com/pharo-graphics/Toplo/assets/3044265/fea4fe4a-a020-4a7d-8a2f-fd803aaa627d">

**Comment by plantec** [comment]
what is the status of this issue ?

**Comment by tinchodias** [comment]
Ah this is closed by https://github.com/pharo-graphics/Bloc/pull/549
